store:
  image: mongo
  ports:
   - 27017
core:
  build: .
  ports:
    - "3000:3000"
  links:
    - store
web:
  build: ../cp-web
  ports:
    - "80:80"
  links:
    - core

#  volumes:
#   - "/data/db:/data/db"
# web:
  # image: "cp/web"
